package com.vtence.kabinet

import com.natpryce.hamkrest.assertion.assertThat
import com.natpryce.hamkrest.equalTo
import kotlin.test.Test

class InsertStatementTest {
    @Test
    fun `inserts columns in target table, ignoring autogenerated columns`() {
        val insert = InsertStatement(Products, listOf(55555555, "Bobtail", "A clever dog"))

        assertThat(
            "raw sql", insert.asSql(), equalTo(
                "INSERT INTO products(number, name, description) VALUES(55555555, 'Bobtail', 'A clever dog')"
            )
        )

        assertThat(
            "prepared sql", insert.asSql(prepared = true), equalTo(
                "INSERT INTO products(number, name, description) VALUES(?, ?, ?)"
            )
        )

        assertThat(
            "arguments", insert.arguments(), equalTo(
                listOf(
                    IntColumnType to 55555555,
                    StringColumnType to "Bobtail",
                    StringColumnType to "A clever dog"
                )
            )
        )
    }
}
