package com.vtence.kabinet

import com.natpryce.hamkrest.assertion.assertThat
import com.natpryce.hamkrest.equalTo
import kotlin.test.Test

class InsertStatementTest {
    @Test
    fun `inserts columns in target table, except autogenerated columns`() {
        val insert = InsertStatement(Products)
        assertThat("sql", insert.toSql(), equalTo("INSERT INTO products(number, name, description) VALUES(?, ?, ?)"))
    }
}
