package com.vtence.kabinet


data class Product(
    val id: Int? = null,
    val number: Int,
    var name: String,
    var description: String? = null
) {
    override fun toString(): String {
        return "$number ($name)"
    }
}

object Products : Table("products") {
    val id = int("id").autoGenerated()
    val number = int("number")
    val name = string("name")
    val description = string("description").nullable()
}


private fun dehydrate(product: Product): Products.(Dataset) -> Unit = {
    it[number] = product.number
    it[description] = product.description
    it[name] = product.name
}

private fun Products.hydrate(row: ResultRow): Product {
    return Product(
        id = row[id],
        number = row[number],
        name = row[name],
        description = row[description]
    )
}

val Product.record: Products.(Dataset) -> Unit
    get() = dehydrate(this)

val ResultRow.product: Product
    get() = Products.hydrate(this)

fun ResultRow.product(alias: String): Product = rebase(Products.alias(alias)).product
