package com.vtence.kabinet

object Products: Table("products") {
    val id = int("id").autoGenerated()
    val number = string("number")
    val name = string("name")
    val description = string("description")
}
