package com.vtence.kabinet

import Product

object Products : Table("products") {
    val id = int("id").autoGenerated()
    val number = string("number")
    val name = string("name")
    val description = string("description")
}


fun dehydrate(product: Product): Products.(Dataset) -> Unit = {
    it[number] = product.number
    it[description] = product.description
    it[name] = product.name
}

val Products.hydrate: ResultRow.() -> Product
    get() = {
        Product(
            id = this[id],
            number = this[number],
            name = this[name],
            // todo nullable/non nullable columns
            description = this[description]
        )
    }


val Product.record get() = dehydrate(this)
val ResultRow.product get() = Products.hydrate(this)
