package com.vtence.kabinet

import Product

object Products : Table("products") {
    val id = int("id").autoGenerated()
    val number = string("number")
    val name = string("name")
    val description = string("description").nullable()
}


object Items : Table("items") {
    val id = int("id").autoGenerated()
    val number = string("number")
}


fun dehydrate(product: Product): Products.(Dataset) -> Unit = {
    it[number] = product.number
    it[description] = product.description
    it[name] = product.name
}

val Products.hydrate: ResultRow.() -> Product
    get() = {
        Product(
            id = this[id],
            number = this[number],
            name = this[name],
            description = this[description]
        )
    }


val Product.record: Products.(Dataset) -> Unit
    get() = dehydrate(this)

val ResultRow.product: Product
    get() = Products.hydrate(this)
