package com.vtence.kabinet


data class Column<T>(private val table: Table, val name: String, val autoGenerated: Boolean = false) {

    fun autoGenerated() = table.replaceColumn(this, copy(autoGenerated = true))
}

