package com.vtence.kabinet


data class Column<T>(
    private val table: Table,
    val name: String,
    private val type: ColumnType<T>,
    val autoGenerated: Boolean = false
): ColumnType<T> by type {

    fun autoGenerated() = table.replaceColumn(this, copy(autoGenerated = true))
}

