package com.vtence.kabinet

import java.sql.ResultSet


class Column<T>(
    val table: Table,
    val name: String,
    val type: ColumnType<T>,
    autoGenerated: Boolean = false,
    nullable: Boolean = false
) : Field<T> {

    val qualifiedName: String = "${table.tableName}.$name"
    val isAutogenerated = autoGenerated
    val isNullable = nullable

    override fun get(rs: ResultSet, index: Int): T? {
        return type.get(rs, index)
    }

    override fun build(statement: SqlBuilder) = statement {
        +qualifiedName
    }

    fun unqualified(): Expression = Expression { it.append(name) }

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is Column<*>) return false

        return table == other.table && name == other.name
    }

    override fun hashCode(): Int = 31 * table.hashCode() + name.hashCode()

    override fun toString(): String = qualifiedName
}
