package com.vtence.kabinet

import java.sql.Connection


class Insert(private val into: Table, private val values: DataChange) {

    private val statement = InsertStatement(into, values.values)

    fun execute(executor: StatementExecutor): KeySet {
        return executor.execute(statement.prepare(values.values) { insert ->
            val inserted = insert.executeUpdate()
            if (inserted > 0)
                KeySet(insert.generatedKeys.read(into.autoGeneratedColumns()))
            else
                KeySet.none()
        })
    }

    override fun toString(): String = statement.asSql()

    companion object {
        fun into(table: Table, values: DataChange): Insert {
            return Insert(table, values)
        }
    }
}

fun Insert.execute(connection: Connection): KeySet = execute(StatementExecutor(connection))


fun <T : Table> T.insert(record: T.(Dataset) -> Unit): Insert =
    Insert.into(this, Dataset.closed(nonAutoGeneratedColumns()).apply { record(this) })
