package com.vtence.kabinet

import java.sql.Connection


class Insert(table: Table, private val values: DataChange) {
    private val statement =
        InsertStatement(table.tableName, table.columns.excludedAutoGenerated().names)

    fun <T> execute(db: StatementExecutor, handleKeys: KeyHandler<T>): T {
        return db.execute(statement.compile { insert ->
            values(insert)
            insert.executeUpdate()
            val keys = insert.generatedKeys.also { it.next() }
            handleKeys(keys)
        })
    }

    override fun toString(): String = statement.toSql()

    companion object {
        fun into(table: Table, values: DataChange): Insert {
            return Insert(table, values)
        }
    }
}

fun Insert.execute(connection: Connection): Int = execute(StatementExecutor(connection))

fun Insert.execute(db: StatementExecutor): Int = execute(db, id)

fun <T> Insert.execute(connection: Connection, handleKeys: KeyHandler<T>): T =
    execute(StatementExecutor(connection), handleKeys)


fun <T : Table> T.insert(record: T.(Dataset) -> Unit): Insert =
    Insert.into(this, Dataset.closed(columns.excludedAutoGenerated()).apply { record(this) })
