package com.vtence.kabinet

import java.sql.Connection
import java.sql.PreparedStatement
import java.sql.Statement.*


interface Preparable {
    fun <T> prepare(execute: (PreparedStatement) -> T): JdbcStatement<T>
}


interface JdbcStatement<T> {
    fun execute(connection: Connection): T

    fun toSql(prepared: Boolean): String
}


class PreparedJdbcStatement<T>(
    private val statement: SqlStatement,
    private val execute: (PreparedStatement) -> T,
    generateKeys: Boolean
) : JdbcStatement<T> {

    private val autoGeneratedKeys = if (generateKeys) RETURN_GENERATED_KEYS else NO_GENERATED_KEYS

    override fun execute(connection: Connection): T {
        val prepared = connection.prepareStatement(statement.toSql(true), autoGeneratedKeys)
        prepared.set(statement.arguments())
        return prepared.use(execute)
    }

    override fun toSql(prepared: Boolean): String {
        return statement.toSql(prepared)
    }
}


interface StatementExecutor {
    fun <T> execute(statement: JdbcStatement<T>): T

    companion object {
        operator fun invoke(connection: Connection): StatementExecutor {
            return object : StatementExecutor {
                override fun <T> execute(statement: JdbcStatement<T>): T {
                    return statement.execute(connection)
                }
            }
        }
    }
}



