package com.vtence.kabinet

import java.sql.ResultSet


interface Field<T> : Expression {
    fun get(rs: ResultSet, index: Int): T?
}


interface FieldSet : Expression {
    val source: ColumnSet

    val fields: List<Field<*>>
}


interface ColumnSet : FieldSet {
    val columns: List<Column<*>>

    override val fields: List<Field<*>> get() = columns
}

fun ColumnSet.autoGeneratedColumns(): List<Column<*>> = columns.filter { it.autoGenerated }

fun ColumnSet.nonAutoGeneratedColumns(): List<Column<*>> = columns - autoGeneratedColumns()


open class Table(name: String) : ColumnSet {
    open val tableName = name
    private val _columns = mutableListOf<Column<*>>()

    override val source: ColumnSet get() = this
    override val columns: List<Column<*>> get() = _columns

    override fun build(statement: SqlStatement) = statement {
        +tableName
    }

    fun int(name: String): Column<Int> = add(Column(this, name, IntColumnType))

    fun string(name: String): Column<String> = add(Column(this, name, StringColumnType))

    @Suppress("UNCHECKED_CAST")
    open operator fun <T : Any?> get(column: Column<T>): Column<T> =
        columns.find { it == column } as? Column<T> ?: error("Column `$column` not found in table `$tableName`")

    private fun <T> add(column: Column<T>): Column<T> = column.also { _columns += it }

    fun replaceColumn(old: Column<*>, new: Column<*>): Unit = with(_columns) {
        remove(old)
        add(new)
    }
}


class Slice(override val source: ColumnSet, override val fields: List<Field<*>>) : FieldSet {
    override fun build(statement: SqlStatement) = statement {
        +source
    }
}

class Projection(override val source: Table, columns: List<Column<*>>) : ColumnSet {
    override val columns: List<Column<*>> = columns.map { source[it] }

    override fun build(statement: SqlStatement) = statement {
        +source
    }
}

fun Table.slice(field: Field<*>, vararg more: Field<*>): FieldSet = slice(listOf(field) + more)

fun Table.slice(fields: List<Field<*>>): FieldSet = Slice(this, fields)

fun Table.slice(column: Column<*>, vararg more: Column<*>): ColumnSet = slice(listOf(column) + more)

fun Table.slice(columns: List<Column<*>>): ColumnSet = Projection(this, columns)
